### ISSUE TITLE
검색기능 API 요청 최적화

### ISSUE THREAD

**Issue by mintmin0320** [uju-in/lime-frontend#60]
## 도입 계기
- 검색 키워드 입력 시 과도한 요청 발생

<br/>
<hr/>
<br/>

@yeeeerim 
현재 요청이 너무 많이 발생하는 것 같아서 이전처럼 빠르게 자동완성 검색어를 확인할 수는 없겠지만 지연 시간을 좀 조정해서 **debounce or throttle** 중 하나를 적용하면 좋을 것 같은데,
의견 남겨주시면 PR 올리도록 하겠습니다 🙂

<br/>
<hr/>
<br/>

## 기존
![화면-기록-2024-05-03-오후-12 30 33](https://github.com/uju-in/lime-frontend/assets/114549939/f1f2d226-0401-48cd-8d95-723fa9825081)

<br/>

## debounce (300ms 딜레이)
![화면-기록-2024-05-03-오후-12 31 35](https://github.com/uju-in/lime-frontend/assets/114549939/29eeea67-58d5-4c41-b617-e5f8f9056d27)

<br/>

## throttle (300ms 딜레이)
![화면-기록-2024-05-03-오후-12 32 00](https://github.com/uju-in/lime-frontend/assets/114549939/ca2238d5-299a-4d79-80cd-de370b83680c)

<br/>
<hr/>

## 참고
- [debounce VS throttle](https://pks2974.medium.com/throttle-%EC%99%80-debounce-%EA%B0%9C%EB%85%90-%EC%A0%95%EB%A6%AC%ED%95%98%EA%B8%B0-2335a9c426ff)

**Comment by yeeeerim** [comment]
@mintmin0320 

관련하여 내용 찾아보니 저희 같은 경우엔 `debounce` 를 사용하는 것이 좋을 것 같은데,
의견 있으실까요?!
